food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    #/food/
    path('', views.IndexClassView.as_view(),name='index'),
    #/food/1
    path('<int:pk>/',views.DetailClassView.as_view(),name='detail'),
    path('item/',views.items,name='item'),
    path('add/',views.CreateClassView.as_view(),name="create_item"),
    path('update/<int:id>/',views.update_item,name="update_item"),
    path('delete/<int:id>/',views.delete_item,name="delete_item"),

]

foodmenu/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

urlpatterns += [

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete = models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=400)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default = " https://img.etimg.com/thumb/msid-65511444,width-643,imgsize-487093,resizemode-4/food-eat-bbq-meat-gettyimages-673139382.jpg ")

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length = 100)

    def __str___(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView



def index(request):
    item_list=Item.objects.all()
    context = {
        'item_list':item_list,
    }
    return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def items(request):
    return HttpResponse('<h1>This is an chocolate cake</h1>')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    return render(request,'food/detail.html',context)

class DetailClassView(DetailView):
    model = Item
    template_name = 'food/detail.html'

# converted to class based create view

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

class CreateClassView(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)



def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = form.cleaned_data.get('username')
            messages.success(request,f'Welcome { user_name } , you are now a member of Foodie Adda family!!! We are excited to have you with us.')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Menu</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
      <a href="#" class="navbar-brand">Foodie Adda</a>
      <div class="navbar">
        <a class="nav-item nav-link" href="{% url 'food:create_item'%}">Add item</a>
        <a class="nav-item nav-link" href="#">Menu item</a>
        <a class="nav-item nav-link" href="#">Delete item</a>
        {% if user.is_authenticated %}
          <a class="nav-item nav-link" href = "{% url 'logout' %}">Logout</a>
          <a class="nav-item nav-link" href = "{% url 'profile' %}">User Profile</a>
        {% else %}
          <a href = "{% url 'login' %}">Login</a>
        {% endif %}
      </div>

    </nav>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert={{ message.tags }}">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    {% block body %}

    {% endblock %}
  </body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

  <div class="container">
    <div class="row m-5">
      <div class="col-md-6">
        <img src="{{ item.item_image }}" class="card" height="300px"/>
      </div>
      <div class="col-md-6">
        <h1>{{ object.item_name }}</h1>
        <h3>{{ object.item_desc }}</h3>
        <h4>{{ object.item_price }}</h4>
        <a href = "{% url 'food:delete_item' item.id %}" class="btn btn-danger">Delete Item</a>
      </div>
    </div>
  </div>


{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}

  {% for item in item_list %}
    <div class="row m-5">
      <div class="col-md-3 offset-md-2">
        <img class="card" src="{{ item.item_image }}" height="200px" width="270px" alt="Image coming soon"/>
      </div>
      <div class="col-md-4">
        <h3>{{ item.item_name }}</h3>
        <h5>{{ item.item_desc }}</h5>
        <h6>${{ item.item_price }}</h6>
        <h6>{{ item.user_name }}</h6>

      </div>
      <div class="col-md-2">
        <a href = "{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

      </div>
    </div>
    
  {% endfor %}
{% endblock %}

food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <h2>Are you sure you want to delete {{ item.item_name }}</h2>
  <button type="submit">Confirm</button>
</form>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {‌{ form }}
                        <button class="btn-info" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
<div class = "container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header text-white bg-info">
          <div class="card-title">
            Login
          </div>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                {{ field.name }}
                {{ field }}
              </div>
            {% endfor %}

              <button class="btn-info offset-md-4" type="submit">Login</button>
            
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

users/templates/users/logout.html
<h1> You have been logged out . </h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src = "{{ user.profile.image.url }}">

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
<div class = "container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header text-white bg-info">
          <div class="card-title">
            Register
          </div>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                {{ field.name }}
                {{ field }}
              </div>
            {% endfor %}

            <button class="btn-info offset-md-4" type="submit">Login</button>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}